#!/usr/bin/env node
// caddy/scripts/dump-config.mjs
// Dump live Caddyfile generated by caddy-docker-proxy.
//
// Flags:
//   --dry-run   Show what would be done
//   --silent    Suppress output
import { execSync } from "node:child_process";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { detectDocker, dockerCmd } from "../../scripts/runners/_docker.mjs";

const args = process.argv.slice(2);
const DRY_RUN = args.includes("--dry-run");
const SILENT = args.includes("--silent");
const log = (...a) => { if (!SILENT) console.log(...a); };

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");
process.chdir(ROOT);

const docker = detectDocker();
if (!docker.available) { console.error("ERROR: Docker not found."); process.exit(1); }

function sh(cmd) {
  try { return execSync(cmd, { cwd: ROOT, stdio: ["pipe", "pipe", "pipe"] }).toString().trim(); }
  catch { return ""; }
}

if (DRY_RUN) { log("[DRY RUN] Would dump caddy config"); process.exit(0); }

const running = sh(dockerCmd("compose ps --status running --services"));
if (!running.split("\n").includes("caddy")) {
  console.error("ERROR: caddy is not running");
  process.exit(1);
}

const hasCmd = sh(dockerCmd("compose exec -T caddy sh -c 'command -v caddy >/dev/null'"));
if (hasCmd) {
  const cfg = sh(dockerCmd("compose exec -T caddy caddy adapt --config /config/caddy/Caddyfile.autosave"))
    || sh(dockerCmd("compose exec -T caddy wget -qO- http://127.0.0.1:2019/config/"))
    || sh(dockerCmd("compose logs --no-color --tail=80 caddy"));
  log(cfg);
} else {
  log(sh(dockerCmd("compose logs --no-color --tail=80 caddy")));
}
